feat(lessonpage): criar pagina de aula
rodlmoraes/homeworkout pull request #10
Opened 2020-10-26 01:32 UTC by JoaoFukuda

Com vídeo caso o vídeo seja do youtube

Precisa melhorar o back-end para poder melhor servir à essa página

2020-10-26 01:50 UTC, rodlmoraes requested changes

2020-10-26 01:50 UTC, rodlmoraes commented on app/javascript/pages/LessonPage.tsx
> +export default function LessonList({match}) {
```suggestion
export default function LessonPage({ match }) {
```

2020-10-26 01:50 UTC, rodlmoraes commented on app/javascript/pages/LessonPage.tsx
> +  return data[0]
Mano, acho q isso nem sempre funciona como vc quer

2020-10-26 01:50 UTC, rodlmoraes commented on app/javascript/services/api.ts
> +  baseURL: baseURLs[process.env.NODE_ENV] || 'https://arcane-fjord-39570.herokuapp.com/api',
volta aqui pra como tava

2020-10-26 01:50 UTC, rodlmoraes commented on cj.json
> +
q isso?

2020-10-26 01:50 UTC, rodlmoraes commented on config/application.rb
> +    config.hosts << "eae040012893.ngrok.io"
e isso?

2020-10-26 01:50 UTC, rodlmoraes commented on config/routes.rb
> +  get '/aula/:id', to: 'pages#fallback'
a ideia era fazer a parada pelo router do react mesmo, acho q ele nem cai nesse caso na real

2020-10-26 01:50 UTC, rodlmoraes commented on app/services/lessons/list.rb
> +        .or(Lesson.includes(:teacher).where(id: @query))
o legal seria num serviço separa

2020-10-26 02:01 UTC, JoaoFukuda commented on app/services/lessons/list.rb
> +        .or(Lesson.includes(:teacher).where(id: @query))
Sim, mas isso de fazer um serviço novo eu vou deixar pro @rogerzs fazer.

2020-10-26 02:02 UTC, JoaoFukuda commented on config/routes.rb
> +  get '/aula/:id', to: 'pages#fallback'
Ele tava dando problema sem isso aí

O `/:route` n pega o caso de subpastas

2020-10-26 02:02 UTC, JoaoFukuda commented on config/application.rb
> +    config.hosts << "eae040012893.ngrok.io"
puts, foi sem querer

2020-10-26 02:03 UTC, JoaoFukuda commented on cj.json
> +
é para o curl, eu vou tirar isso agora, perae

2020-10-26 02:03 UTC, JoaoFukuda commented on app/javascript/services/api.ts
> +  baseURL: baseURLs[process.env.NODE_ENV] || 'https://arcane-fjord-39570.herokuapp.com/api',
Ok

2020-10-26 12:29 UTC, rodlmoraes requested changes
só pra lembrar, por alguma razão ta quebrando o Travis CI, então mesmo ser mergear ele não vai chegar na master

2020-10-26 12:29 UTC, rodlmoraes commented on app/services/lessons/list.rb
> +        .or(Lesson.includes(:teacher).where(id: @query))
bele

2020-10-26 13:51 UTC, rodlmoraes requested changes

2020-10-26 13:51 UTC, rodlmoraes commented on app/javascript/services/api.ts
> +  baseURL: baseURLs[process.env.NODE_ENV] || 'https://127.0.0.1:64793/api',
era só http, não https

2020-10-26 13:51 UTC, rodlmoraes commented on app/services/lessons/list.rb
> +        .or(Lesson.includes(:teacher).where(id: @query))
agora q já tem o outro pode tirar isso e arrumar a call no front

2020-10-26 13:51 UTC, rodlmoraes commented on app/javascript/pages/LessonPage.tsx
> +      link: string
aqui não vai chegar tudo isso nesse match, vai chegar o id, o resto vc pega na requisiçao eu ahco

2020-10-26 14:02 UTC, JoaoFukuda commented on app/javascript/pages/LessonPage.tsx
> +  return data[0]
Eu sei, mas o @rogerzs ta fazendo um end-point no back-end para fazer essa requisição

2020-11-09 00:10 UTC, JoaoFukuda commented on app/javascript/pages/LessonPage.tsx
> +      link: string
E como faz isso?

2020-11-09 02:22 UTC, rodlmoraes commented on app/controllers/api/lessons_controller.rb
> +    end
tem 2 vezes o mesmo método

2020-11-09 02:23 UTC, rodlmoraes commented on app/javascript/pages/LessonPage.tsx
> +      link: string
vc recebe o id e faz a requisição pra api com o id

2020-11-09 02:23 UTC, rodlmoraes commented on app/javascript/pages/LessonPage.tsx
> +  return data[0]
agr q já tem usa la

2020-11-09 02:24 UTC, rodlmoraes commented on app/services/lessons/list.rb
> +        .or(Lesson.includes(:teacher).where(id: @query))
já da pra tirar

2020-11-09 02:24 UTC, rodlmoraes commented on app/javascript/services/api.ts
> +  baseURL: baseURLs[process.env.NODE_ENV] || 'http://127.0.0.1:64793/api',
muda não q vai dar pau em outras parada

2020-11-09 02:25 UTC, rodlmoraes commented on config/application.rb
> +    config.hosts << "eae040012893.ngrok.io"
.

2020-11-09 04:27 UTC, JoaoFukuda commented on app/javascript/pages/LessonPage.tsx
> +  return data[0]
ok

2020-11-09 04:44 UTC, JoaoFukuda commented on app/javascript/services/api.ts
> +  baseURL: baseURLs[process.env.NODE_ENV] || 'http://127.0.0.1:64793/api',
aaah ok
eu acho que passou sem querer em algum merge conflict

2020-11-09 04:46 UTC, JoaoFukuda commented on config/application.rb
> +    config.hosts << "eae040012893.ngrok.io"
feito...

2020-11-09 04:47 UTC, JoaoFukuda commented on config/application.rb
> +    config.hosts << "eae040012893.ngrok.io"
eu tava usando esse arquivo por isso n tava vendo que ele ainda n tafa arrumado
Oops

2020-11-09 04:53 UTC, JoaoFukuda commented
Acho que agora, depois de **14** dias da para dar um merge nessa branch...

2020-11-09 04:58 UTC, JoaoFukuda commented
Atualização: O TravisCI [aceitou o PR](https://travis-ci.org/github/rodlmoraes/homeworkout/builds/742351418), mas por algum motivo o github não pegou, então... já está pronto para dar o merge, so birra msm. ;)
Vou dormir pq n aguento mais. Até amanhã!

2020-11-09 11:48 UTC, rodlmoraes approved these changes

2020-11-09 11:48 UTC, merged