feat(list): remover link do card e arrumar estilo
rodlmoraes/homeworkout pull request #31
Opened 2020-11-22 23:09 UTC by JoaoFukuda

2020-11-23 01:27 UTC, rodlmoraes requested changes
só ve essa parada do travis não passar ai

2020-11-23 12:34 UTC, JoaoFukuda commented
> só ve essa parada do travis não passar ai

Ele só n rodou ainda, mas aqui tava passando.

É só esperar.

2020-11-23 12:40 UTC, JoaoFukuda commented
Agora passa

2020-11-24 19:44 UTC, rodlmoraes approved these changes

2020-11-24 19:45 UTC, merged